### PR TITLE
rpm kabi compatible checks propose

### PR DESCRIPTION
**Pull request by Hui-Zhi**

### CODE REVIEW

**Comment by sbahling** [comment]
About the first bullet, I don't think we need to run a check against the SLE kernel kABI - at least that would not be a priority.
Important is to check that kernel module package has kernel symbols listed in requires and that those match the symbols of the modules in the package.
The idea is that we are just checking that the kernel module package is built properly.
The check should not be run on kernel packages but just rpms providing additional kernel modules.

**Comment by Hui-Zhi** [comment]
> About the first bullet, I don't think we need to run a check against the SLE kernel kABI - at least that would not be a priority.
> Important is to check that kernel module package has kernel symbols listed in requires and that those match the symbols of the modules in the package.
> The idea is that we are just checking that the kernel module package is built properly.
> The check should not be run on kernel packages but just rpms providing additional kernel modules.

The ```modules``` you mean ```drivers```, right?

**Comment by Hui-Zhi** [comment]
> > > About the first bullet, I don't think we need to run a check against the SLE kernel kABI - at least that would not be a priority.
> > > Important is to check that kernel module package has kernel symbols listed in requires and that those match the symbols of the modules in the package.
Thank you.  I know how to check the rpm symbols listed in requires, but how can I get the symbols of the modules in the package?

> > > The idea is that we are just checking that the kernel module package is built properly.
> > > The check should not be run on kernel packages but just rpms providing additional kernel modules.
> > 
> > 
> > The `modules` you mean `drivers`, right?
> 
> Yes. it's a more general term for kernel loadable modules whereas `drivers` tends to refer to kernel modules that are device drivers. Though `modules` and `drivers` are commonly used interchangeably.

**Comment by Hui-Zhi** [comment]
> > > About the first bullet, I don't think we need to run a check against the SLE kernel kABI - at least that would not be a priority.
> > > Important is to check that kernel module package has kernel symbols listed in requires and that those match the symbols of the modules in the package.
> > > The idea is that we are just checking that the kernel module package is built properly.
> > > The check should not be run on kernel packages but just rpms providing additional kernel modules.
> > 
> > 
> > The `modules` you mean `drivers`, right?
> 
> Yes. it's a more general term for kernel loadable modules whereas `drivers` tends to refer to kernel modules that are device drivers. Though `modules` and `drivers` are commonly used interchangeably.

Thank you, I know how to get the symbols listed in the rpm requires, but how can I get the symbols of the modules in the package

**Pull request merged**
